### ISSUE TITLE
How

### ISSUE THREAD

**Issue by TheMysteryKnight** [mend-dev/BTD6Rogue#6]
![20230804190229_1](https://github.com/mend-dev/BTD6Rogue/assets/130113599/0a7b391b-0129-464f-acb4-71667b2e8d00)

**Comment by MommaBear091992** [comment]
yes this is what keeps happening to me with the new updates! the last like 3 or 4 updates do this to me!

**Comment by TheMysteryKnight** [comment]
[12:42:31.109] [BloonsTD6_Mod_Helper] System.NullReferenceException: Object reference not set to an instance of an object.
   at BTD_Mod_Helper.Extensions.TowerModelExt.GetUpgradeLevel(TowerModel towerModel, Int32 path)
   at BTD6Rogue.TowerUtil.DuplicatePath(TowerModel tower) in /home/runner/work/BTD6Rogue/BTD6Rogue/BTD6Rogue/Util/TowerUtil.cs:line 41
   at BTD6Rogue.TowerUtil.GetThreeTowers(Int32 maxPath, Boolean waterMap) in /home/runner/work/BTD6Rogue/BTD6Rogue/BTD6Rogue/Util/TowerUtil.cs:line 31
   at BTD6Rogue.TowerChoicePanel.Create(RectTransform menu, InGame __instance) in /home/runner/work/BTD6Rogue/BTD6Rogue/BTD6Rogue/Panels/TowerChoicePanel.cs:line 77
   at BTD6Rogue.RoundEndPatch.Postfix(InGame __instance, Int32 completedRound, Int32 highestCompletedRound) in /home/runner/work/BTD6Rogue/BTD6Rogue/BTD6Rogue/Patches/RoundEndPatch.cs:line 47
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame::RoundEnd>(InGame this, Int32 completedRound, Int32 highestCompletedRound)
   at (il2cpp -> managed) RoundEnd(IntPtr , Int32 , Int32 , Il2CppMethodInfo* )

**Comment by mend-dev** [comment]
I'll look into it, I can't seem to replicate the bug on my end, but I'll see what I can do. If you remember all the mods you were using at the same time when this occurred and any errors in console, that'd be helpful
